# -*- coding: utf-8 -*-
"""Youtube_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UK4CagWm4tKEfVPoV0CNK78cpfP6DMiB
"""

!pip install -q --no-cache-dir \
  "youtube-transcript-api==1.2.4" \
  "langchain==0.2.16" \
  "langchain-community==0.2.16" \
  "langchain-openai==0.1.23" \
  "langchain-core==0.2.43" \
  "faiss-cpu" \
  "sentence-transformers" \
  "openai==1.30.0"

import os
import time
from typing import List
from sentence_transformers import SentenceTransformer
from langchain.embeddings.base import Embeddings
from youtube_transcript_api import YouTubeTranscriptApi
from langchain.docstore.document import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_openai import ChatOpenAI
from langchain_community.vectorstores import FAISS
from langchain.memory import ConversationBufferMemory
from langchain.chains import ConversationalRetrievalChain

# --------------------------------------------------------------
# APNI OPENROUTER KEY YAHAN DAALO
OPENROUTER_API_KEY = "sk-or-"
# --------------------------------------------------------------

os.environ["OPENAI_API_KEY"]  = OPENROUTER_API_KEY
os.environ["OPENAI_API_BASE"] = "https://openrouter.ai/api/v1"

FREE_MODELS = [
    "nvidia/nemotron-3-super-120b-a12b:free",
    "openai/gpt-oss-20b:free",
    "qwen/qwen3-4b:free",
    "google/gemma-3n-e4b-it:free",
    "arcee-ai/trinity-mini:free",
    "liquid/lfm-2.5-1.2b-instruct:free"
]

# --------------------------------------------------------------
# Custom Embeddings
# --------------------------------------------------------------
class SentenceTransformerEmbeddings(Embeddings):
    def __init__(self, model_name: str = "all-MiniLM-L6-v2"):
        self.model = SentenceTransformer(model_name)

    def embed_documents(self, texts: List[str]) -> List[List[float]]:
        return self.model.encode(texts, show_progress_bar=False).tolist()

    def embed_query(self, text: str) -> List[float]:
        return self.model.encode([text], show_progress_bar=False)[0].tolist()

# --------------------------------------------------------------
# Function 1 - Video ID extract
# --------------------------------------------------------------
def get_video_id(url_or_id: str) -> str:
    url_or_id = url_or_id.strip()
    if "youtube.com/watch?v=" in url_or_id:
        return url_or_id.split("v=")[1].split("&")[0]
    elif "youtu.be/" in url_or_id:
        return url_or_id.split("youtu.be/")[1].split("?")[0]
    return url_or_id

# --------------------------------------------------------------
# Function 2 - Transcript fetch
# --------------------------------------------------------------
def fetch_transcript(url_or_id: str) -> str:
    video_id = get_video_id(url_or_id)
    print(f"Video ID: {video_id}")
    ytt = YouTubeTranscriptApi()

    for lang in [["en"], ["hi"], None]:
        try:
            if lang is not None:
                fetched = ytt.fetch(video_id, languages=lang)
                print(f"Transcript mila. Language: {lang[0]}")
            else:
                transcript_list = ytt.list(video_id)
                first = next(iter(transcript_list))
                fetched = ytt.fetch(video_id, languages=[first.language_code])
                print(f"Transcript mila. Language: {first.language}")
            break
        except Exception:
            if lang is None:
                raise Exception("Koi bhi transcript nahi mila.")
            print(f"{lang[0]} transcript nahi mila, agli language try kar raha hoon...")

    full_text = " ".join([s.text for s in fetched])
    print(f"Total characters: {len(full_text)}")
    return full_text

# --------------------------------------------------------------
# Function 3 - VectorStore
# --------------------------------------------------------------
def build_vectorstore(text: str):
    doc = Document(page_content=text)
    chunks = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=150
    ).split_documents([doc])
    print(f"Chunks ready: {len(chunks)}")
    print("Embeddings load ho rahi hain...")
    embeddings = SentenceTransformerEmbeddings("all-MiniLM-L6-v2")
    vs = FAISS.from_documents(chunks, embeddings)
    print("VectorStore ready.")
    return vs

# --------------------------------------------------------------
# Function 4 - Chain with auto fallback
# --------------------------------------------------------------
def build_chain(vs):
    for model in FREE_MODELS:
        try:
            print(f"Model try kar raha hoon: {model}")
            llm = ChatOpenAI(
                model=model,
                temperature=0.3,
                openai_api_key=OPENROUTER_API_KEY,
                openai_api_base="https://openrouter.ai/api/v1",
                default_headers={
                    "HTTP-Referer": "https://colab.research.google.com",
                    "X-Title": "YouTube Chatbot"
                }
            )
            llm.invoke("Say hi in one word")
            print(f"Model working: {model}")

            memory = ConversationBufferMemory(
                memory_key="chat_history",
                return_messages=True,
                output_key="answer"
            )
            chain = ConversationalRetrievalChain.from_llm(
                llm=llm,
                retriever=vs.as_retriever(search_kwargs={"k": 4}),
                memory=memory,
                return_source_documents=False,
                verbose=False
            )
            print("Chain ready.")
            return chain

        except Exception as e:
            print(f"Model failed: {model} -- {str(e)[:80]}")
            time.sleep(2)

    raise Exception("Koi bhi model available nahi hai abhi.")

VIDEO_URL = "https://www.youtube.com/watch?v=LPZh9BOjkQs"

print("-" * 55)
print("YouTube Chatbot shuru ho raha hai...")
print("-" * 55)

text  = fetch_transcript(VIDEO_URL)
vs    = build_vectorstore(text)
chain = build_chain(vs)

print("\nSummary ban rahi hai...\n")
res = chain.invoke({
    "question": "Is video ka ek accha aur detailed summary do. Sare main points cover karo."
})
print("VIDEO SUMMARY:")
print("-" * 55)
print(res["answer"])
print("-" * 55)
print("\nChatbot ready. ")

print("\nChatbot ready. Koi bhi sawaal poocho.")
print("'quit' likhne par band hoga.")
print("-" * 55 + "\n")

while True:
    try:
        q = input("Tum: ").strip()
    except EOFError:
        break

    if not q:
        continue

    if q.lower() in ["quit", "exit", "bye", "band karo"]:
        print("Theek hai, bye.")
        break

    print("Soch raha hoon...\n")
    res = chain.invoke({"question": q})
    print(f"Bot: {res['answer']}")
    print("-" * 55 + "\n")